package reversotranslate

var (
	lang = []string{
		"Arabic",
		"Chinese (Simplified)",
		"Czech",
		"Danish",
		"Dutch",
		"English",
		"French",
		"German",
		"Greek",
		"Hebrew",
		"Hindi",
		"Hungarian",
		"Italian",
		"Japanese",
		"Korean",
		"Persian",
		"Polish",
		"Portuguese",
		"Romanian",
		"Russian",
		"Slovak",
		"Spanish",
		"Swedish",
		"Thai",
		"Turkish",
		"Ukrainian",
	}
	langCode = map[string]string{
		"Arabic":               "ara",
		"Chinese (Simplified)": "chi",
		"Czech":                "cze",
		"Danish":               "dan",
		"Dutch":                "dut",
		"English":              "eng",
		"French":               "fra",
		"German":               "ger",
		"Greek":                "gre",
		"Hebrew":               "heb",
		"Hindi":                "hin",
		"Hungarian":            "hun",
		"Italian":              "ita",
		"Japanese":             "jpn",
		"Korean":               "kor",
		"Persian":              "per",
		"Polish":               "pol",
		"Portuguese":           "por",
		"Romanian":             "rum",
		"Russian":              "rus",
		"Slovak":               "slo",
		"Spanish":              "spa",
		"Swedish":              "swe",
		"Thai":                 "tha",
		"Turkish":              "tur",
		"Ukrainian":            "ukr",
	}
)
