package apertiumtranslate

var (
	lang = []string{
		"Afrikaans",
		"Arabic",
		"Aranese",
		"Aragonese",
		"Arpitan",
		"Basque",
		"Belarusian",
		"Breton",
		"Bulgarian",
		"Catalan",
		"Crimean Tatar",
		"Danish",
		"Dutch",
		"East Norwegian, vi→vi",
		"English",
		"Esperanto",
		"French",
		"Galician",
		"Gascon",
		"Hindi",
		"Icelandic",
		"Indonesian",
		"Italian",
		"Kazakh",
		"Macedonian",
		"Malay",
		"Maltese",
		"Northern Sami",
		"Norwegian Bokmål",
		"Norwegian Nynorsk",
		"Occitan",
		"Polish",
		"Portuguese",
		"Romanian",
		"Russian",
		"Serbo-Croatian",
		"Silesian",
		"Slovenian",
		"Spanish",
		"Swedish",
		"Tatar",
		"Turkish",
		"Ukrainian",
		"Urdu",
		"Welsh",
	}
	langCode = map[string]string{
		"Afrikaans":             "afr",
		"Arabic":                "ara",
		"Aranese":               "oci_aran",
		"Aragonese":             "arg",
		"Arpitan":               "frp",
		"Basque":                "eus",
		"Belarusian":            "bel",
		"Breton":                "bre",
		"Bulgarian":             "bul",
		"Catalan":               "cat",
		"Crimean Tatar":         "crh",
		"Danish":                "dan",
		"Dutch":                 "nld",
		"East Norwegian, vi→vi": "nno_e",
		"English":               "eng",
		"Esperanto":             "epo",
		"French":                "fra",
		"Galician":              "glg",
		"Gascon":                "oci_gascon",
		"Hindi":                 "hin",
		"Icelandic":             "isl",
		"Indonesian":            "ind",
		"Italian":               "ita",
		"Kazakh":                "kaz",
		"Macedonian":            "mkd",
		"Malay":                 "zlm",
		"Maltese":               "mlt",
		"Northern Sami":         "sme",
		"Norwegian Bokmål":      "nob",
		"Norwegian Nynorsk":     "nno",
		"Occitan":               "oci",
		"Polish":                "pol",
		"Portuguese":            "por",
		"Romanian":              "ron",
		"Russian":               "rus",
		"Serbo-Croatian":        "hbs",
		"Silesian":              "szl",
		"Slovenian":             "slv",
		"Spanish":               "spa",
		"Swedish":               "swe",
		"Tatar":                 "tat",
		"Turkish":               "tur",
		"Ukrainian":             "ukr",
		"Urdu":                  "urd",
		"Welsh":                 "cym",
	}
)
