package chatgpt

var (
	// Generated from Bing
	lang = []string{
		"Afrikaans",
		"Albanian",
		"Amharic",
		"Auto",
		"Arabic",
		"Armenian",
		"Assamese",
		"Azerbaijani",
		"Bangla",
		"Bashkir",
		"Basque",
		"Bosnian",
		"Bulgarian",
		"Cantonese (Traditional)",
		"Catalan",
		"Chinese (Literary)",
		"Chinese Simplified",
		"Chinese Traditional",
		"Croatian",
		"Czech",
		"Danish",
		"Dari",
		"Divehi",
		"Dutch",
		"English",
		"Estonian",
		"Faroese",
		"Fijian",
		"Filipino",
		"Finnish",
		"French",
		"French (Canada)",
		"Galician",
		"Ganda",
		"Georgian",
		"German",
		"Greek",
		"Gujarati",
		"Haitian Creole",
		"Hausa",
		"Hebrew",
		"Hindi",
		"Hmong Daw",
		"Hungarian",
		"Icelandic",
		"Igbo",
		"Indonesian",
		"Inuinnaqtun",
		"Inuktitut",
		"Inuktitut (Latin)",
		"Irish",
		"Italian",
		"Japanese",
		"Kannada",
		"Kazakh",
		"Khmer",
		"Kinyarwanda",
		"Klingon (Latin)",
		"Korean",
		"Kurdish (Central)",
		"Kurdish (Northern)",
		"Kyrgyz",
		"Lao",
		"Latvian",
		"Lingala",
		"Lithuanian",
		"Macedonian",
		"Malagasy",
		"Malay",
		"Malayalam",
		"Maltese",
		"Marathi",
		"Mongolian (Cyrillic)",
		"Mongolian (Traditional)",
		"Myanmar (Burmese)",
		"Māori",
		"Nepali",
		"Norwegian",
		"Nyanja",
		"Odia",
		"Pashto",
		"Persian",
		"Polish",
		"Portuguese (Brazil)",
		"Portuguese (Portugal)",
		"Punjabi",
		"Querétaro Otomi",
		"Romanian",
		"Rundi",
		"Russian",
		"Samoan",
		"Serbian (Cyrillic)",
		"Serbian (Latin)",
		"Sesotho",
		"Sesotho sa Leboa",
		"Setswana",
		"Shona",
		"Slovak",
		"Slovenian",
		"Somali",
		"Spanish",
		"Swahili",
		"Swedish",
		"Tahitian",
		"Tamil",
		"Tatar",
		"Telugu",
		"Thai",
		"Tibetan",
		"Tigrinya",
		"Tongan",
		"Turkish",
		"Turkmen",
		"Ukrainian",
		"Urdu",
		"Uyghur",
		"Uzbek (Latin)",
		"Vietnamese",
		"Welsh",
		"Xhosa",
		"Yoruba",
		"Yucatec Maya",
		"Zulu",
	}
)
