package libre

var (
	lang = []string{
		"Albanian",
		"Arabic",
		"Auto",
		"Azerbaijani",
		"Bengali",
		"Bulgarian",
		"Catalan",
		"Chinese",
		"Chinese (traditional)",
		"Czech",
		"Danish",
		"Dutch",
		"English",
		"Esperanto",
		"Estonian",
		"Finnish",
		"French",
		"German",
		"Greek",
		"Hebrew",
		"Hindi",
		"Hungarian",
		"Indonesian",
		"Irish",
		"Italian",
		"Japanese",
		"Korean",
		"Latvian",
		"Lithuanian",
		"Malay",
		"Norwegian",
		"Persian",
		"Polish",
		"Portuguese",
		"Romanian",
		"Russian",
		"Slovak",
		"Slovenian",
		"Spanish",
		"Swedish",
		"Tagalog",
		"Thai",
		"Turkish",
		"Ukranian",
		"Urdu",
	}
	langCode = map[string]string{
		"Albanian":              "sq",
		"Arabic":                "ar",
		"Auto":                  "auto",
		"Azerbaijani":           "az",
		"Bengali":               "bn",
		"Bulgarian":             "bg",
		"Catalan":               "ca",
		"Chinese":               "zh",
		"Chinese (traditional)": "zt",
		"Czech":                 "cs",
		"Danish":                "da",
		"Dutch":                 "nl",
		"English":               "en",
		"Esperanto":             "eo",
		"Estonian":              "et",
		"Finnish":               "fi",
		"French":                "fr",
		"German":                "de",
		"Greek":                 "el",
		"Hebrew":                "he",
		"Hindi":                 "hi",
		"Hungarian":             "hu",
		"Indonesian":            "id",
		"Irish":                 "ga",
		"Italian":               "it",
		"Japanese":              "ja",
		"Korean":                "ko",
		"Latvian":               "lv",
		"Lithuanian":            "lt",
		"Malay":                 "ms",
		"Norwegian":             "nb",
		"Persian":               "fa",
		"Polish":                "pl",
		"Portuguese":            "pt",
		"Romanian":              "ro",
		"Russian":               "ru",
		"Slovak":                "sk",
		"Slovenian":             "sl",
		"Spanish":               "es",
		"Swedish":               "sv",
		"Tagalog":               "tl",
		"Thai":                  "th",
		"Turkish":               "tr",
		"Ukranian":              "uk",
		"Urdu":                  "ur",
	}
)
