package bing

var (
	lang = []string{
		"Afrikaans",
		"Albanian",
		"Amharic",
		"Auto",
		"Arabic",
		"Armenian",
		"Assamese",
		"Azerbaijani",
		"Bangla",
		"Bashkir",
		"Basque",
		"Bosnian",
		"Bulgarian",
		"Cantonese (Traditional)",
		"Catalan",
		"Chinese (Literary)",
		"Chinese Simplified",
		"Chinese Traditional",
		"Croatian",
		"Czech",
		"Danish",
		"Dari",
		"Divehi",
		"Dutch",
		"English",
		"Estonian",
		"Faroese",
		"Fijian",
		"Filipino",
		"Finnish",
		"French",
		"French (Canada)",
		"Galician",
		"Ganda",
		"Georgian",
		"German",
		"Greek",
		"Gujarati",
		"Haitian Creole",
		"Hausa",
		"Hebrew",
		"Hindi",
		"Hmong Daw",
		"Hungarian",
		"Icelandic",
		"Igbo",
		"Indonesian",
		"Inuinnaqtun",
		"Inuktitut",
		"Inuktitut (Latin)",
		"Irish",
		"Italian",
		"Japanese",
		"Kannada",
		"Kazakh",
		"Khmer",
		"Kinyarwanda",
		"Klingon (Latin)",
		"Korean",
		"Kurdish (Central)",
		"Kurdish (Northern)",
		"Kyrgyz",
		"Lao",
		"Latvian",
		"Lingala",
		"Lithuanian",
		"Macedonian",
		"Malagasy",
		"Malay",
		"Malayalam",
		"Maltese",
		"Marathi",
		"Mongolian (Cyrillic)",
		"Mongolian (Traditional)",
		"Myanmar (Burmese)",
		"Māori",
		"Nepali",
		"Norwegian",
		"Nyanja",
		"Odia",
		"Pashto",
		"Persian",
		"Polish",
		"Portuguese (Brazil)",
		"Portuguese (Portugal)",
		"Punjabi",
		"Querétaro Otomi",
		"Romanian",
		"Rundi",
		"Russian",
		"Samoan",
		"Serbian (Cyrillic)",
		"Serbian (Latin)",
		"Sesotho",
		"Sesotho sa Leboa",
		"Setswana",
		"Shona",
		"Slovak",
		"Slovenian",
		"Somali",
		"Spanish",
		"Swahili",
		"Swedish",
		"Tahitian",
		"Tamil",
		"Tatar",
		"Telugu",
		"Thai",
		"Tibetan",
		"Tigrinya",
		"Tongan",
		"Turkish",
		"Turkmen",
		"Ukrainian",
		"Urdu",
		"Uyghur",
		"Uzbek (Latin)",
		"Vietnamese",
		"Welsh",
		"Xhosa",
		"Yoruba",
		"Yucatec Maya",
		"Zulu",
	}
	langCode = map[string]string{
		"Afrikaans":               "af",
		"Albanian":                "sq",
		"Amharic":                 "am",
		"Auto":                    "auto-detect",
		"Arabic":                  "ar",
		"Armenian":                "hy",
		"Assamese":                "as",
		"Azerbaijani":             "az",
		"Bangla":                  "bn",
		"Bashkir":                 "ba",
		"Basque":                  "eu",
		"Bosnian":                 "bs",
		"Bulgarian":               "bg",
		"Cantonese (Traditional)": "yue",
		"Catalan":                 "ca",
		"Chinese (Literary)":      "lzh",
		"Chinese Simplified":      "zh-Hans",
		"Chinese Traditional":     "zh-Hant",
		"Croatian":                "hr",
		"Czech":                   "cs",
		"Danish":                  "da",
		"Dari":                    "prs",
		"Divehi":                  "dv",
		"Dutch":                   "nl",
		"English":                 "en",
		"Estonian":                "et",
		"Faroese":                 "fo",
		"Fijian":                  "fj",
		"Filipino":                "fil",
		"Finnish":                 "fi",
		"French":                  "fr",
		"French (Canada)":         "fr-CA",
		"Galician":                "gl",
		"Ganda":                   "lug",
		"Georgian":                "ka",
		"German":                  "de",
		"Greek":                   "el",
		"Gujarati":                "gu",
		"Haitian Creole":          "ht",
		"Hausa":                   "ha",
		"Hebrew":                  "he",
		"Hindi":                   "hi",
		"Hmong Daw":               "mww",
		"Hungarian":               "hu",
		"Icelandic":               "is",
		"Igbo":                    "ig",
		"Indonesian":              "id",
		"Inuinnaqtun":             "ikt",
		"Inuktitut":               "iu",
		"Inuktitut (Latin)":       "iu-Latn",
		"Irish":                   "ga",
		"Italian":                 "it",
		"Japanese":                "ja",
		"Kannada":                 "kn",
		"Kazakh":                  "kk",
		"Khmer":                   "km",
		"Kinyarwanda":             "rw",
		"Klingon (Latin)":         "tlh-Latn",
		"Korean":                  "ko",
		"Kurdish (Central)":       "ku",
		"Kurdish (Northern)":      "kmr",
		"Kyrgyz":                  "ky",
		"Lao":                     "lo",
		"Latvian":                 "lv",
		"Lingala":                 "ln",
		"Lithuanian":              "lt",
		"Macedonian":              "mk",
		"Malagasy":                "mg",
		"Malay":                   "ms",
		"Malayalam":               "ml",
		"Maltese":                 "mt",
		"Marathi":                 "mr",
		"Mongolian (Cyrillic)":    "mn-Cyrl",
		"Mongolian (Traditional)": "mn-Mong",
		"Myanmar (Burmese)":       "my",
		"Māori":                   "mi",
		"Nepali":                  "ne",
		"Norwegian":               "nb",
		"Nyanja":                  "nya",
		"Odia":                    "or",
		"Pashto":                  "ps",
		"Persian":                 "fa",
		"Polish":                  "pl",
		"Portuguese (Brazil)":     "pt",
		"Portuguese (Portugal)":   "pt-PT",
		"Punjabi":                 "pa",
		"Querétaro Otomi":         "otq",
		"Romanian":                "ro",
		"Rundi":                   "run",
		"Russian":                 "ru",
		"Samoan":                  "sm",
		"Serbian (Cyrillic)":      "sr-Cyrl",
		"Serbian (Latin)":         "sr-Latn",
		"Sesotho":                 "st",
		"Sesotho sa Leboa":        "nso",
		"Setswana":                "tn",
		"Shona":                   "sn",
		"Slovak":                  "sk",
		"Slovenian":               "sl",
		"Somali":                  "so",
		"Spanish":                 "es",
		"Swahili":                 "sw",
		"Swedish":                 "sv",
		"Tahitian":                "ty",
		"Tamil":                   "ta",
		"Tatar":                   "tt",
		"Telugu":                  "te",
		"Thai":                    "th",
		"Tibetan":                 "bo",
		"Tigrinya":                "ti",
		"Tongan":                  "to",
		"Turkish":                 "tr",
		"Turkmen":                 "tk",
		"Ukrainian":               "uk",
		"Urdu":                    "ur",
		"Uyghur":                  "ug",
		"Uzbek (Latin)":           "uz",
		"Vietnamese":              "vi",
		"Welsh":                   "cy",
		"Xhosa":                   "xh",
		"Yoruba":                  "yo",
		"Yucatec Maya":            "yua",
		"Zulu":                    "zu",
	}
	voiceName = map[string]string{
		"Afrikaans":               "af-ZA-AdriNeural",
		"Amharic":                 "am-ET-MekdesNeural",
		"Arabic":                  "ar-SA-HamedNeural",
		"Bangla":                  "bn-IN-TanishaaNeural",
		"Bulgarian":               "bg-BG-BorislavNeural",
		"Cantonese (Traditional)": "zh-HK-HiuGaaiNeural",
		"Catalan":                 "ca-ES-JoanaNeural",
		"Chinese Simplified":      "zh-CN-XiaoxiaoNeural",
		"Chinese Traditional":     "zh-CN-XiaoxiaoNeural",
		"Croatian":                "hr-HR-SreckoNeural",
		"Czech":                   "cs-CZ-AntoninNeural",
		"Danish":                  "da-DK-ChristelNeural",
		"Dutch":                   "nl-NL-ColetteNeural",
		"English":                 "en-US-AriaNeural",
		"Estonian":                "et-EE-AnuNeural",
		"Finnish":                 "fi-FI-NooraNeural",
		"French":                  "fr-FR-DeniseNeural",
		"French (Canada)":         "fr-CA-SylvieNeural",
		"German":                  "de-DE-KatjaNeural",
		"Greek":                   "el-GR-NestorasNeural",
		"Gujarati":                "gu-IN-DhwaniNeural",
		"Hebrew":                  "he-IL-AvriNeural",
		"Hindi":                   "hi-IN-SwaraNeural",
		"Hungarian":               "hu-HU-TamasNeural",
		"Icelandic":               "is-IS-GudrunNeural",
		"Indonesian":              "id-ID-ArdiNeural",
		"Irish":                   "ga-IE-OrlaNeural",
		"Italian":                 "it-IT-DiegoNeural",
		"Japanese":                "ja-JP-NanamiNeural",
		"Kannada":                 "kn-IN-SapnaNeural",
		"Kazakh":                  "kk-KZ-AigulNeural",
		"Khmer":                   "km-KH-SreymomNeural",
		"Korean":                  "ko-KR-SunHiNeural",
		"Lao":                     "lo-LA-KeomanyNeural",
		"Latvian":                 "lv-LV-EveritaNeural",
		"Lithuanian":              "lt-LT-OnaNeural",
		"Macedonian":              "mk-MK-MarijaNeural",
		"Malay":                   "ms-MY-OsmanNeural",
		"Malayalam":               "ml-IN-SobhanaNeural",
		"Maltese":                 "mt-MT-GraceNeural",
		"Marathi":                 "mr-IN-AarohiNeural",
		"Myanmar (Burmese)":       "my-MM-NilarNeural",
		"Norwegian":               "nb-NO-PernilleNeural",
		"Pashto":                  "ps-AF-LatifaNeural",
		"Persian":                 "fa-IR-DilaraNeural",
		"Polish":                  "pl-PL-ZofiaNeural",
		"Portuguese (Brazil)":     "pt-BR-FranciscaNeural",
		"Portuguese (Portugal)":   "pt-PT-FernandaNeural",
		"Romanian":                "ro-RO-EmilNeural",
		"Russian":                 "ru-RU-DariyaNeural",
		"Serbian (Cyrillic)":      "sr-RS-SophieNeural",
		"Slovak":                  "sk-SK-LukasNeural",
		"Slovenian":               "sl-SI-RokNeural",
		"Spanish":                 "es-ES-ElviraNeural",
		"Swedish":                 "sv-SE-SofieNeural",
		"Tamil":                   "ta-IN-PallaviNeural",
		"Telugu":                  "te-IN-ShrutiNeural",
		"Thai":                    "th-TH-NiwatNeural",
		"Turkish":                 "tr-TR-EmelNeural",
		"Ukrainian":               "uk-UA-PolinaNeural",
		"Urdu":                    "ur-IN-GulNeural",
		"Uzbek (Latin)":           "uz-UZ-MadinaNeural",
		"Vietnamese":              "vi-VN-NamMinhNeural",
		"Welsh":                   "cy-GB-NiaNeural",
	}
)
